messages:
    basename: i18n/login
server:
  port: 8081
spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:mysql://localhost:3306/jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema:
      - classpath:department.sql